### ISSUE TITLE
Broken Back Button

### ISSUE THREAD

**Issue by publicsafetydan** [Sujimichi/KerbalX#6]
I continue to have an issue with using the back button on this site. Specifically I access the site from http://www.kerbalx.com/KSpaceAcademy/craft and click on any of the craft listed. If I am on the first page and click the back button, it will reload the first page just fine. However if I have loaded more craft, and open one of them, i get a 404 error when using the back button.

I am running windows 8.1, and using the latest Waterfox browser.

Please let me know if I can be of any additional assistance.

**Comment by Sujimichi** [comment]
Thanks for reporting this. I believe the issue comes from the url have www. in it. 
I've now set up a redirect from www.kerbalx.com to kerbalx.com (something I've been meaning to do, but hadn't got round to).  That should sort this issue out.  Let me know if that fixes the back button issue or not.  Thanks!
